### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by joystick** [minical/minical#195]
Hi there Minical Team, how's it going?

Could you please tell more about API?
I see API key generated in Minical.
I see v1 and v2 in controllers under api folder. 
Is there any description hiding on how to access/modify data? 🤔

Thanks for great tool 👍

**Comment by pankaj9296** [comment]
Hi @joystick,
we are currently working on API documentation. It should be available on miniCal documentation soon:
https://docs.minical.io

**Comment by m0dE** [comment]
awesome. thanks @pankaj9296 !
