### ISSUE TITLE
Unable to have settings for both Hostel & Hotel in a single property 

### ISSUE THREAD

**Issue by avvi-mane** [minical/minical#198]
Hi, I’ve a property with both Dormitory & Private rooms.

From the hostel example I was only able to setup the web portal for individual beds

I thought the `settings` key in the JSON configuration is a json array. Instead it appears to be json object.

I was to add both `room` and `bed` to `settings.unit_name`

**Comment by matas0** [comment]
Hello, yes that would be possible. You can setup each bed as a separate room and use a different type for each of them.

If you need more help feel free to ask in the discord server.
