### ISSUE TITLE
Language_translation_helper ERROR

### ISSUE THREAD

**Issue by pabloap101sp** [minical/minical#214]
A PHP Error was encountered
Severity: Notice
Message: Undefined property: Booking::$all_translations_data
Filename: helpers/language_translation_helper.php
Line Number: 162

I have this error post install
![Screenshot 2022-04-13 at 22-11-01 Hotel Plaza](https://user-images.githubusercontent.com/103614787/163294519-f9018b97-bef1-4750-9070-12b4c18ac316.png)

**Comment by mraduljain** [comment]
Hi, Are you still facing this issue?
