### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by triminio20** [minical/minical#251]
I need some help with the installation on my local server, I'm using php 8.3, mysql 5x thanks for your timely help
![error](https://user-images.githubusercontent.com/31413691/197303678-180e88d2-4318-4223-9d61-637f112677af.jpg)
![error2](https://user-images.githubusercontent.com/31413691/197303680-9b1be30a-8143-493f-8d10-16143437fe23.jpg)
![error3](https://user-images.githubusercontent.com/31413691/197303681-255be8cf-c94e-493e-9ba7-784011b4d3fc.jpg)
![error4](https://user-images.githubusercontent.com/31413691/197303682-7b642f37-cda5-4a04-8794-2726ef5a1b29.jpg)

**Comment by triminio20** [comment]
I have made a change in the .env file moving the configuration to production and now it gives me this error
![error5](https://user-images.githubusercontent.com/31413691/197306006-76015b8a-ecb0-4a9e-a958-b5fc33e40cee.jpg)

**Comment by triminio20** [comment]
this is the response sent by the server 
<br />
<b>Fatal error</b>:  Uncaught mysqli_sql_exception: Table 'minical.minical_installation_meta' doesn't exist in C:\xampp\htdocs\minical\public\install\database_seeding.php:36
Stack trace:
#0 C:\xampp\htdocs\minical\public\install\database_seeding.php(36): mysqli_query(Object(mysqli), 'SELECT pointer ...')
#1 {main}
  thrown in <b>C:\xampp\htdocs\minical\public\install\database_seeding.php</b> on line <b>36</b><br />

**Comment by triminio20** [comment]
help please

**Comment by mraduljain** [comment]
@triminio20, I think, you should use PHP 7.3 OR 7.4 version. 
Minical is not supporting PHP 8 OR more than PHP 8 version as of now.

**Comment by triminio20** [comment]
I have installed the version of php that you suggest, but now it gives me the following error
![1](https://user-images.githubusercontent.com/31413691/198066848-d99d4fd1-09f5-4d13-a34f-ebf072e90f06.png)

**Comment by mraduljain** [comment]
@triminio20,
I f you are comfortable then can we do it by Anydesk?

**Comment by sifaw23** [comment]
> I have made a change in the .env file moving the configuration to production and now it gives me this error ![error5](https://user-images.githubusercontent.com/31413691/197306006-76015b8a-ecb0-4a9e-a958-b5fc33e40cee.jpg)

can you please help me to run mincal i been trying but i couldn't 
Thank you

**Comment by yogi9016** [comment]
all the css, js, images, fonts are not loading during the local setup

![image](https://user-images.githubusercontent.com/27411502/221515114-0a569dd1-b44e-4fb9-8f68-17cc4f800358.png)

My Nginx conf file

server {
    listen       80;
    server_name  minical.test;

    root   /project/minical;
    index  index.php index.html index.htm;

    location ~* ^/public/(css|fonts|images|js)/ {}
    location ~* ^/.*/assets/.* {}

    location / {
        rewrite ^/api/(.*)$ /api/index.php?/$1 last;
        rewrite ^/public/(.*)$ /public/index.php?/$1 last;
        try_files $uri $uri/ /index.php?/$request_uri;
        if ($uri ~ ".(jpg|png|css|js|appcache|xml|ogg|m4a)$"){
            set $rule_0 1$rule_0;
        } 
    }
    
    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9074;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        # increase default buffers and timeouts
        fastcgi_buffers 8 16k;       # default is 8 4k|8k
        fastcgi_buffer_size 32k;     # default is 4k|8k
        fastcgi_connect_timeout 60s; # default is 60s
        fastcgi_send_timeout 300s;   # default is 60s
        fastcgi_read_timeout 300s;   # default is 60s
    }
    location ~* ^/(assets|files|robots\.txt) { }
    location ~ /\.ht {
        deny  all;
    }
    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }
}


![Screenshot 2023-02-27 at 2 15 16 PM](https://user-images.githubusercontent.com/27411502/221515935-debaf703-fa02-47f1-867b-2a9f39059fb9.png)

Kindly help to sort this out.

Thank You

**Comment by cldxciv** [comment]
@mraduljain I have fixed everything for php 8 but I am still getiing the seeding failed when I am trying to install can you please suggest something.

**Comment by uttkarsh1012** [comment]
Is there a reliable fix for the data-seeding failure? This issue seems widespread, and I’m currently stuck with the same problem. I’ve exhausted all available guidance, including online resources and official documentation, but none of the steps have helped.

<img width="1050" height="664" alt="Image" src="https://github.com/user-attachments/assets/76cf9df2-ad5b-40d8-b45e-8fe7f881e75f" />

**Comment by uttkarsh1012** [comment]
Thank you,@mraduljain it worked php 7.4 and MariaDB 10.4

I think we should update docker file 
from

  db:
        image: mariadb:latest

to. 

  db:
        image: mariadb:10.4


as well as update composer.json
so it strict composer update to version 7.4, it was updating to newer version before for me (doing this fix my issue by restricting php version to 7.4)

{
  "require": {
    "php": "^7.4",
    "stripe/stripe-php": "^7.77",
    "vlucas/phpdotenv": "^4.2",
    "lifenpag/asaas-php": "^1.0",
    "sonata-project/google-authenticator": "^2.3"
  },
  "require-dev": {
    "friendsofphp/php-cs-fixer": "^3.0"
  },
  "config": {
    "platform": {
      "php": "7.4.33"
    }
  }
}
