### ISSUE TITLE
env

### ISSUE THREAD

**Issue by sanalisci** [minical/minical#278]
hello, i did all run the composer but it stuck here, it dont see env file which i already entered all credentials

Required Environment Variables (Configured in .env file)
--
DATABASE_HOST |   | Database Host Name.Mysql container name if setting inside a Docker container. | Database host name is not configure

**Comment by harshbinjwa** [comment]
@sanalisci 
please confirm that your env file is properly created with .env file extension 
and place it at the root of minical folder.
