### ISSUE TITLE
Need more information on SMTP setup in self host

### ISSUE THREAD

**Issue by lumintulogic-admin** [minical/minical#282]
Need help in setting up SMTP. I have configured my SMTP credentials and tried different values for SMTP_CRYPTO in .env (tried ssl, tls, and empty), the frontend says that the email is sent, but nothing is sent to the destination email address.

**Comment by ochotzas** [comment]
Issue still on-going...but issue closed. [Harshbinjwa](https://github.com/harshbinjwa) could you provide some information about the resolution?
