### ISSUE TITLE
Docker: Fatal Error while accessing the installation page

### ISSUE THREAD

**Issue by gerryflux** [minical/minical#283]
I have followed the instructions on how to self-host using docker. I have adapted all the necessary changes in the .env and yaml file too. I still, however, have been pulling my hair out getting it to work, I keep getting this Error while trying to access the installation page and completely stuck.
http://[10.1.1.1:8080/public/install/index.php](http://10.1.1.1:8080/public/install/index.php)

![image](https://github.com/minical/minical/assets/52464120/1149138a-484b-4e1e-a588-6f7aec8bd284)

I also believe the docker installation could be improved, perhaps having a single docker image we could pull from some registry?

**Comment by harshbinjwa** [comment]
hi gerryflux,
Try installing docker with the specific version.
RUN pecl install xdebug-2.7.0 && docker-php-ext-enable xdebug

**Comment by GregTroar** [comment]
Also same issue here, changing to RUN pecl install xdebug-2.7.0 && docker-php-ext-enable xdebug did not solve the issue

**Comment by AzpektDev** [comment]
running `composer require vlucas/phpdotenv` fixed it for me
