### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [minical/minical#288]
Dear @minical team,

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/p/minical/

To disable/delete tabs, go here: https://sourceforge.net/projects/minical/
To add a new tab, go here: https://sourceforge.net/projects/minical/
To change informations, go here: https://sourceforge.net/p/minical/admin/overview
To export, go here: https://sourceforge.net/p/minical/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/minical/admin/overview
- A new tab, go here: https://sourceforge.net/projects/minical/

To add the good website...

Time to remove:
- https://sourceforge.net/p/open-source-hotel-software-pms/tickets/
- https://sourceforge.net/p/open-source-hotel-software-pms/code/
- https://sourceforge.net/p/open-source-hotel-software-pms/wiki/

Thanks in advance.

**Comment by harshbinjwa** [comment]
hi Neustradamus,
will think about it. thanks for the advice.

**Comment by Neustradamus** [comment]
@harshbinjwa: The solution was not to remove all... :/

**Comment by Neustradamus** [comment]
Dear @minical, @harshbinjwa,

I wish you a Happy New Year 2024!

Sorry, I have edited the links.

Any progress on it?

It is not solved, can you reopen this ticket?

Thanks in advance.

**Comment by Neustradamus** [comment]
Dear @minical team, @harshbinjwa, @m0dE,

I wish you a Happy New Year 2024!

Sorry, I have edited the links in description, there were bad.

Have you progressed on it?

It is not solved, can you reopen this ticket?

Thanks in advance.

Note: Today, I have sent an email to @m0dE directly on Sourceforge because no changes since several weeks.
