### ISSUE TITLE
 Error on data base installation step - Common.php on line 350 - Input.php on line 391

### ISSUE THREAD

**Issue by adeljeljeli** [minical/minical#289]
hello , i need help , I have this error on data base installation step :  

Deprecated: Optional parameter $level declared before required parameter $message is implicitly treated as a required parameter in /home/bpvducdj/pms.adeljeljeli.tn/public/system/core/Common.php on line 350

Fatal error: Uncaught TypeError: filter_var(): Argument #3 ($options) must be of type array|int, string given in /home/bpvducdj/pms.adeljeljeli.tn/public/system/core/Input.php:391 Stack trace: #0 /home/bpvducdj/pms.adeljeljeli.tn/public/system/core/Input.php(391): filter_var() #1 /home/bpvducdj/pms.adeljeljeli.tn/public/system/core/Input.php(354): CI_Input->valid_ip() #2 /home/bpvducdj/pms.adeljeljeli.tn/public/application/libraries/MY_Session.php(122): CI_Input->ip_address() #3 /home/bpvducdj/pms.adeljeljeli.tn/public/application/libraries/MY_Session.php(64): MY_Session->sess_create() #4 /home/bpvducdj/pms.adeljeljeli.tn/public/system/core/Loader.php(1099): MY_Session->__construct() #5 /home/bpvducdj/pms.adeljeljeli.tn/public/system/core/Loader.php(938): CI_Loader->_ci_init_class() #6 /home/bpvducdj/pms.adeljeljeli.tn/public/system/core/Loader.php(216): CI_Loader->_ci_load_class() #7 /home/bpvducdj/pms.adeljeljeli.tn/public/system/core/Loader.php(1178): CI_Loader->library() #8 /home/bpvducdj/pms.adeljeljeli.tn/public/system/core/Loader.php(152): CI_Loader->_ci_autoloader() #9 /home/bpvducdj/pms.adeljeljeli.tn/public/application/core/MY_Loader.php(67): CI_Loader->initialize() #10 /home/bpvducdj/pms.adeljeljeli.tn/public/system/core/Controller.php(51): MY_Loader->initialize() #11 /home/bpvducdj/pms.adeljeljeli.tn/public/application/controllers/migrate.php(32): CI_Controller->__construct() #12 /home/bpvducdj/pms.adeljeljeli.tn/public/system/core/CodeIgniter.php(308): Migrate->__construct() #13 /home/bpvducdj/pms.adeljeljeli.tn/public/index.php(233): require_once('/home/bpvducdj/...') #14 {main} thrown in /home/bpvducdj/pms.adeljeljeli.tn/public/system/core/Input.php on line 391

Database seeding failed!
 I use 8.2 php version

**Comment by harshbinjwa** [comment]
hello adeljeljeli
use PHP 7.3 with MySQL DB 10.4 
that will work for you.

**Comment by ochotzas** [comment]
Are we gonna have support for like `PHP>=8.0`?
