### ISSUE TITLE
Multiple currency

### ISSUE THREAD

**Issue by Trex5** [minical/minical#51]
There is no section to set and change rates for multiple currencies. When selecting and setting the rates in rates management you can choose multiple rates but in accounting the system combines all currencies as one.

**Comment by m0dE** [comment]
Thanks for your feedback. Would you like a feature where you can just simply enable certain currencies, and the rates will be automatically adjusted based on conversion rate?
If so, do you want a table where you can add conversion rate for each currencies?
if you could exaplain/provide example of how this can be done properly, that'd be very helpful!
thanks.

**Comment by Trex5** [comment]
Hi, I think a table that one can enable certain currencies and set their conversion rate based on a certain period of time would be perfect. something that would look like the settings for the room rates panel that one can set rooms rates in a given period. This is due to that most hotels have their own conversion rates and these mainly are slightly higher than the on going global rates. These are usually set to allow room for market fluctuations so as to not affect the books of the property. so a rate may last for months or days depending on the country and property. This will also help when referring  back example a sale done a month ago when the exchange rate between two currencies was 1:20 will still remain the same in the reports when the current rate has changed to 1:22. 

Keep up the good work, this is one of the best softwares for Property management.
